version: "3"
# Services are a type of container
services: 
    # container name
    redis-server:
        # image name
        image: "redis"
        # container name
    node-app:
        # Restart policy
        restart: always
        # means build this container with the DockerFile in this folder
        build: .
        # port mapping
        # '-' means array
        ports:
            - "4001:8081"