version: "3"
# Services are a type of container
services: 
    # container name
    web:
        # Restart policy
        restart: always
        # means build this container with the DockerFile in this folder
        build: 
            # Where we want all the files and folders to be pulled from
            context: .
            dockerfile: Dockerfile.dev
        # port mapping
        # '-' means array
        ports:
            - "3000:3000"
        environment: 
            - VAR=test
    # this service is used solely for running tests
    # tests:
    #     build: 
    #         context: .
    #         dockerfile: Dockerfile.dev
    #     volumes: 
    #         - /home/node/app/node_modules
    #         - .:/home/node/app
    #     # override the start up command in a container
    #     command: ["npm", "run", "test"]