FROM node:14.14.0-alpine
WORKDIR /home/node/app
COPY package.json .
RUN npm install --loglevel=warn;
USER node
COPY . .

# Tell the image  what to do when it starts as a container
CMD ["npm", "run", "start"]